=== pablo603/XML-repo--bueno-/Cliente/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT clientes (sede)*>
<!ELEMENT sede (empleado|fech_alta|desc_cliente|cliente)*>
<!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fech_alta (#PCDATA)>
<!ELEMENT desc_cliente (#PCDATA)>
<!ELEMENT cliente (num_viviendas|coste_vivienda|resumen_vivienda|plazo_alta)*>
<!ATTLIST cliente codigo CDATA #REQUIRED>
<!ELEMENT num_viviendas (#PCDATA)>
<!ELEMENT coste_vivienda (#PCDATA)>
<!ELEMENT resumen_vivienda (#PCDATA)>
<!ELEMENT plazo_alta (#PCDATA)>

=== pablo603/XML-repo--bueno-/Cliente/Clientes.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo = "C1234567">
        <empleado> Juan </empleado>
        <fech_alta> 20/01/21 </fech_alta>
        <desc_cliente> sovente </desc_cliente>
            <cliente codigo = "ABD-123">
                <num_viviendas> 4 </num_viviendas>
                <coste_vivienda> 50000 </coste_vivienda>
                <resumen_vivienda> buena calidad </resumen_vivienda>
                <plazo_alta> 20/14/14 </plazo_alta>
            </cliente>
    </sede>  
</clientes>
